Naming/FileName:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
AllCops:
  Exclude:
    - 'spec/factories/test_factory.rb'
    - 'spec/support/db/schema.rb'
    - 'spec/support/test_db.rb'
    - 'spec/**/*_spec.rb'
